name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build PDF
        run: pdflatex -interaction=nonstopmode resume.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: ./resume.pdf
