name: Resume CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build PDF
        run: pdflatex -interaction=nonstopmode -jobname=luchian-mihai-cv-tex resume.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv-tex
          path: ./luchian-mihai-cv-tex.pdf
